trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/iaac/azure'
    backendType: 'azurerm'
    backendServiceArm: 'VoteApp ARM'
    backendAzureRmSubscriptionId: '58748300-daee-4162-a4a4-bc9d55d91416'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'tfstate_voteApp'
    backendAzureRmResourceGroupLocation: 'northeurope'
    backendAzureRmStorageAccountName: 'tfstate_voteApp'
    backendAzureRmStorageAccountSku: 'Standard_LRS'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev-terraform-voteApp.tfstate'
    allowTelemetryCollection: false
